sudo: false

language: node_js

notifications:
  email:
    recipients:
      - devcenter@docusign.com
    on_success: never
    on_failure: change

node_js:
  - "2.1.16"
  - "3"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"

